- title: "Dry Sea"
  role: "Concept Artist"
  type: "Animation"
  year: 2022
  image: "/assets/img/productions/InterstellarElla_Poster.jpg"

- title: "Ninja Express"
  role: "3D Artist"
  type: "Short Film"
  year: 2023
  image: "/assets/img/productions/InterstellarElla_Poster.jpg"

- title: "Sir Mouse"
  role: "Concept Artist"
  type: "Animation"
  year: 2022
  image: "/assets/img/productions/InterstellarElla_Poster.jpg"

- title: "Interstellar Ella"
  role: "3D Artist"
  type: "Short Film"
  year: 2023
  image: "/assets/img/productions/InterstellarElla_Poster.jpg"