name: Oussama Mahieddine
email: Oussama.mahieddine@outlook.com
#
about:
   description: Oussama Mahieddine is a 2d/3d artist.
   contact: Cantact information
#socials
instagram_path: https://www.instagram.com/samam4
artstation_path: https://www.artstation.com/sama
