# About
name: Oussama Mahieddine
email: Oussama.mahieddine@outlook.com
# Socials
instagram_path: https://www.instagram.com/samam4
artstation_path: https://www.artstation.com/sama


# Portfolio
artstation_img_dir: https://cdnb.artstation.com/p/assets/images/images
countess_off_robotville:
hellboy_good_samaritan:
patty_wagen:
