# About
name: Oussama Mahieddine
email: Oussama.mahieddine@outlook.com
# Socials
instagram_path: https://www.instagram.com/samam4
artstation_path: https://www.artstation.com/sama


# Portfolio
artstation_img_dir: https://cdnb.artstation.com/p/assets/images/images

# sketchbook:
#   img: https://cdna.artstation.com/p/assets/images/images/013/345/044/large/oussama-mahieddine-boompjes.jpg?1539177181
#   img: https://cdnb.artstation.com/p/assets/images/images/013/344/871/large/oussama-mahieddine-sadgurl.jpg?1539176646
#   img: https://cdna.artstation.com/p/assets/images/images/013/344/820/large/oussama-mahieddine-artemis01.jpg?1539176465
#   img: https://cdna.artstation.com/p/assets/images/images/013/367/034/large/oussama-mahieddine-boi-sketch.jpg?1539265525
#   img: https://cdnb.artstation.com/p/assets/images/images/013/345/103/large/oussama-mahieddine-demondude.jpg?1539177315
#   img: https://cdnb.artstation.com/p/assets/images/images/013/367/659/large/oussama-mahieddine-demone.jpg?1539267135
