# About
name: Oussama Mahieddine
email: Oussama.mahieddine@outlook.com
# Socials
instagram_path: https://www.instagram.com/samam4
artstation_path: https://www.artstation.com/sama


# Portfolio
artstation_img_dir: https://cdnb.artstation.com/p/assets/images/images
countess_off_robotville:
  # Images
  finalver_url: /021/536/405/large/oussama-m-final-version001.jpg?1572048618
  clayrender_url: /021/536/985/large/oussama-m-clayrender.jpg?1572051131
hellboy_good_samaritan:
  url:
patty_wagen:
  url:
